config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :aufgabes
  #get "home/index"
  root "home#index"
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/aufgabe.rb
class Aufgabe < ApplicationRecord
end

app/models/favorite_city.rb
class FavoriteCity < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/aufgabes_controller.rb
class AufgabesController < ApplicationController
  before_action :set_aufgabe, only: %i[ show edit update destroy ]

  # GET /aufgabes or /aufgabes.json
  def index
    @aufgabes = Aufgabe.all
  end

  # GET /aufgabes/1 or /aufgabes/1.json
  def show
  end

  # GET /aufgabes/new
  def new
    @aufgabe = Aufgabe.new
  end

  # GET /aufgabes/1/edit
  def edit
  end

  # POST /aufgabes or /aufgabes.json
  def create
    @aufgabe = Aufgabe.new(aufgabe_params)

    respond_to do |format|
      if @aufgabe.save
        format.html { redirect_to @aufgabe, notice: "Aufgabe was successfully created." }
        format.json { render :show, status: :created, location: @aufgabe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aufgabe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aufgabes/1 or /aufgabes/1.json
  def update
    respond_to do |format|
      if @aufgabe.update(aufgabe_params)
        format.html { redirect_to @aufgabe, notice: "Aufgabe was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @aufgabe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aufgabe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aufgabes/1 or /aufgabes/1.json
  def destroy
    @aufgabe.destroy!

    respond_to do |format|
      format.html { redirect_to aufgabes_path, notice: "Aufgabe was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aufgabe
      @aufgabe = Aufgabe.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def aufgabe_params
      params.expect(aufgabe: [ :aufgabe, :dringlichkeit, :schwierigkeit ])
    end
end

app/controllers/favorite_cities_controller.rb
class FavoriteCitiesController < ApplicationController
  def index
  end
end

app/controllers/favoriten_controller.rb
class FavoritenController < ApplicationController
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    city = params[:city].presence || "Leipzig,de"  # Als Standart ohne Eingabe
    @weather = HTTParty.get(
      "https://api.openweathermap.org/data/2.5/weather",
      query: {
        q:    city,
        lang: "de",
        units: "metric",
        appid: ENV["OPEN_WEATHER_MAP_TOKEN"]
      }
    ).parsed_response
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aufgabes_helper.rb
module AufgabesHelper
end

app/helpers/favorite_cities_helper.rb
module FavoriteCitiesHelper
end

app/helpers/favoriten_helper.rb
module FavoritenHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/aufgabes/_aufgabe.html.erb
<div id="<%= dom_id aufgabe %>">
  <p>
    <strong>Aufgabe:</strong>
    <%= aufgabe.aufgabe %>
  </p>

  <p>
    <strong>Dringlichkeit:</strong>
    <%= aufgabe.dringlichkeit %>
  </p>

  <p>
    <strong>Schwierigkeit:</strong>
    <%= aufgabe.schwierigkeit %>
  </p>

</div>

app/views/aufgabes/_form.html.erb
<%= form_with(model: aufgabe) do |form| %>
  <% if aufgabe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aufgabe.errors.count, "error") %> prohibited this aufgabe from being saved:</h2>

      <ul>
        <% aufgabe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :aufgabe, style: "display: block" %>
    <%= form.text_field :aufgabe %>
  </div>

  <div>
    <%= form.label :dringlichkeit, style: "display: block" %>
    <%= form.text_field :dringlichkeit %>
  </div>

  <div>
    <%= form.label :schwierigkeit, style: "display: block" %>
    <%= form.text_field :schwierigkeit %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aufgabes/edit.html.erb
<% content_for :title, "Editing aufgabe" %>

<h1>Editing aufgabe</h1>

<%= render "form", aufgabe: @aufgabe %>

<br>

<div>
  <%= link_to "Show this aufgabe", @aufgabe %> |
  <%= link_to "Back to aufgabes", aufgabes_path %>
</div>

app/views/aufgabes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Aufgabes" %>

<h1>Aufgabes</h1>

<div id="aufgabes">
  <% @aufgabes.each do |aufgabe| %>
    <%= render aufgabe %>
    <p>
      <%= link_to "Show this aufgabe", aufgabe %>
    </p>
  <% end %>
</div>

<%= link_to "New aufgabe", new_aufgabe_path %>

app/views/aufgabes/new.html.erb
<% content_for :title, "New aufgabe" %>

<h1>New aufgabe</h1>

<%= render "form", aufgabe: @aufgabe %>

<br>

<div>
  <%= link_to "Back to aufgabes", aufgabes_path %>
</div>

app/views/aufgabes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aufgabe %>

<div>
  <%= link_to "Edit this aufgabe", edit_aufgabe_path(@aufgabe) %> |
  <%= link_to "Back to aufgabes", aufgabes_path %>

  <%= button_to "Destroy this aufgabe", @aufgabe, method: :delete %>
</div>

app/views/favorite_cities/index.html.erb
<h1>FavoriteCities#index</h1>
<p>Find me in app/views/favorite_cities/index.html.erb</p>

app/views/home/_header.html.erb
<div class="menü">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Über Uns', home_about_path %>
  <%= link_to 'Aufgaben', aufgabes_path %>

  <% if user_signed_in? %>
    <%= link_to 'Neue Aufgabe', new_aufgabe_path %>
    <%= link_to "Abmelden", destroy_user_session_path, data: { turbo_method: :delete } %>
    <%= link_to 'Profil', edit_user_registration_path %>
  <% else %>
    <%= link_to 'Anmelden', new_user_registration_path %>
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
</div>

app/views/home/about.erb
<h1>Über Uns</h1>
<p>Dokumentation und Download: </p>
<a href="https://github.com/MLGDev" target="_blank">GitHub</a>

app/views/home/index.html.erb
<h1>Willkommen bei DER Wetter App</h1>
<%= form_with url: root_path, method: :get do %>
  <p>
    <%= label_tag :city, "Stadt mit Ländercode eingeben (z.B: Berlin,de):" %><br>
    <%= text_field_tag :city, params[:city] %>
  </p>
  <p>
    <%= submit_tag "Senden", class: "btn" %>
  </p>
<% end %>
<% if @weather.present? %>
  <h2>Wetter in <%= @weather["name"] %></h2>
  <div class="wetter">
    <p>Temperatur: <%= @weather["main"]["temp"].to_f.round(1) %> °C</p>
    <p>Luftfeuchtigkeit: <%= @weather["main"]["humidity"] %> %</p>
    <p>Beschreibung: <%= @weather["weather"][0]["description"].capitalize %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sietman" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'home/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    <br> <br> <br>
    Erstellt 2025 von MLG
  </body>
</html>